/**
 * Control.FP.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.BooleanResponse
import io.swagger.client.models.IngresosDto
import io.swagger.client.models.IngresosDtoListResponse
import io.swagger.client.models.IngresosDtoResponse

import io.swagger.client.infrastructure.*

class IngresoDescriptionApi(basePath: kotlin.String = "/") : ApiClient(basePath) {

    /**
     * 
     * 
     * @return IngresosDtoListResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionGet(): IngresosDtoListResponse {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/IngresoDescription"
        )
        val response = request<IngresosDtoListResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDtoListResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return BooleanResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionIdDelete(id: kotlin.Int): BooleanResponse {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/api/IngresoDescription/{id}".replace("{" + "id" + "}", "$id")
        )
        val response = request<BooleanResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as BooleanResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return IngresosDtoResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionIdGet(id: kotlin.Int): IngresosDtoResponse {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/IngresoDescription/{id}".replace("{" + "id" + "}", "$id")
        )
        val response = request<IngresosDtoResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDtoResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param body  (optional)
     * @return IngresosDtoResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionPost(body: IngresosDto? = null): IngresosDtoResponse {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/api/IngresoDescription"
        )
        val response = request<IngresosDtoResponse>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDtoResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param body  (optional)
     * @return IngresosDtoResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionPut(body: IngresosDto? = null): IngresosDtoResponse {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/api/IngresoDescription"
        )
        val response = request<IngresosDtoResponse>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDtoResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param usuarioId  
     * @return IngresosDtoListResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionUsuarioUsuarioIdGet(usuarioId: kotlin.Int): IngresosDtoListResponse {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/IngresoDescription/usuario/{usuarioId}".replace("{" + "usuarioId" + "}", "$usuarioId")
        )
        val response = request<IngresosDtoListResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDtoListResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
