/**
 * Control.FP.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.BooleanResponse
import io.swagger.client.models.IngresosDescription
import io.swagger.client.models.IngresosDescriptionListResponse
import io.swagger.client.models.IngresosDescriptionResponse

import io.swagger.client.infrastructure.*

class IngresoDescriptionApi(basePath: kotlin.String = "/") : ApiClient(basePath) {

    /**
     * 
     * 
     * @return IngresosDescriptionListResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionGet(): IngresosDescriptionListResponse {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/IngresoDescription"
        )
        val response = request<IngresosDescriptionListResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDescriptionListResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return BooleanResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionIdDelete(id: kotlin.Int): BooleanResponse {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/api/IngresoDescription/{id}".replace("{" + "id" + "}", "$id")
        )
        val response = request<BooleanResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as BooleanResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return IngresosDescriptionResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionIdGet(id: kotlin.Int): IngresosDescriptionResponse {
        
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/IngresoDescription/{id}".replace("{" + "id" + "}", "$id")
        )
        val response = request<IngresosDescriptionResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDescriptionResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param body  (optional)
     * @return IngresosDescriptionResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionPost(body: IngresosDescription? = null): IngresosDescriptionResponse {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/api/IngresoDescription"
        )
        val response = request<IngresosDescriptionResponse>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDescriptionResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param body  (optional)
     * @return IngresosDescriptionResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiIngresoDescriptionPut(body: IngresosDescription? = null): IngresosDescriptionResponse {
        val localVariableBody: kotlin.Any? = body
        
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/api/IngresoDescription"
        )
        val response = request<IngresosDescriptionResponse>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as IngresosDescriptionResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
