/**
 * Control.FP.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.BooleanResponse
import io.swagger.client.models.UsuarioDto
import io.swagger.client.models.UsuarioDto2
import io.swagger.client.models.UsuarioDto2Response
import io.swagger.client.models.UsuarioDtoListResponse
import io.swagger.client.models.UsuarioDtoResponse

import io.swagger.client.infrastructure.*

class UsuarioDescriptionApi(basePath: kotlin.String = "/") : ApiClient(basePath) {

    /**
     * 
     * 
     * @return UsuarioDtoListResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiUsuarioDescriptionGet(): UsuarioDtoListResponse {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/UsuarioDescription"
        )
        val response = request<UsuarioDtoListResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UsuarioDtoListResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return BooleanResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiUsuarioDescriptionIdDelete(id: kotlin.Int): BooleanResponse {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/api/UsuarioDescription/{id}".replace("{" + "id" + "}", "$id")
        )
        val response = request<BooleanResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as BooleanResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return UsuarioDtoResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiUsuarioDescriptionIdGet(id: kotlin.Int): UsuarioDtoResponse {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/api/UsuarioDescription/{id}".replace("{" + "id" + "}", "$id")
        )
        val response = request<UsuarioDtoResponse>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UsuarioDtoResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param body  (optional)
     * @return UsuarioDtoResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiUsuarioDescriptionPost(body: UsuarioDto? = null): UsuarioDtoResponse {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/api/UsuarioDescription"
        )
        val response = request<UsuarioDtoResponse>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UsuarioDtoResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param body  (optional)
     * @return UsuarioDtoResponse
     */
    @Suppress("UNCHECKED_CAST")
    fun apiUsuarioDescriptionPut(body: UsuarioDto? = null): UsuarioDtoResponse {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/api/UsuarioDescription"
        )
        val response = request<UsuarioDtoResponse>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UsuarioDtoResponse
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param body  (optional)
     * @return UsuarioDto2Response
     */
    @Suppress("UNCHECKED_CAST")
    fun apiUsuarioDescriptionUpdate2Put(body: UsuarioDto2? = null): UsuarioDto2Response {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.PUT,
                "/api/UsuarioDescription/update2"
        )
        val response = request<UsuarioDto2Response>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as UsuarioDto2Response
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
