/**
 * Control.FP.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param idUsuario 
 * @param cantidad 
 * @param descripcion 
 * @param fecha 
 */
data class IngresosDto (

    val id: kotlin.Int? = null,
    val idUsuario: kotlin.Int? = null,
    val cantidad: kotlin.Double? = null,
    val descripcion: kotlin.String? = null,
    val fecha: kotlin.String? = null
) {
}