/**
 * Control.FP.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id 
 * @param name 
 * @param password 
 * @param total 
 * @param imagePath 
 */
data class UsuarioDto (

    val id: kotlin.Int? = null,
    val name: kotlin.String? = null,
    val password: kotlin.String? = null,
    val total: kotlin.Double? = null,
    val imagePath: kotlin.String? = null
) {
}