/**
 * Control.FP.Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param date 
 * @param temperatureC 
 * @param temperatureF 
 * @param summary 
 */
data class WeatherForecast (

    val date: java.time.LocalDateTime? = null,
    val temperatureC: kotlin.Int? = null,
    val temperatureF: kotlin.Int? = null,
    val summary: kotlin.String? = null
) {
}